version: '3.1'
services:
  stats-server:
    build: ./stats
    image: liberica-openjdk-alpine:11.0.16.1-1
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme

  stats-db:
    image: postgres:14-alpine

  ewm-service:
    build: ./main
    image: liberica-openjdk-alpine:11.0.16.1-1
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme

  ewm-db:
    image: postgres:14-alpine
