DROP TABLE IF EXISTS USERS, CATEGORIES, EVENTS, COMPILATIONS, REQUESTS;

CREATE TABLE IF NOT EXISTS `USERS`
(
    `ID`    LONG PRIMARY KEY AUTO_INCREMENT,
    `NAME`  VARCHAR(50),
    `EMAIL` VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS `CATEGORIES`
(
    `ID`     LONG PRIMARY KEY AUTO_INCREMENT,
    `NAME`   VARCHAR(50) UNIQUE ,
    `PINNED` VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS `EVENTS`
(
    `ID`                LONG PRIMARY KEY AUTO_INCREMENT,
    `ANNOTATION`        VARCHAR(100),
    `TITLE`             VARCHAR(100),
    `CREATEDON`         DATETIME,
    `DESCRIPTION`       VARCHAR(200),
    `EVENTDATE`         DATETIME,
    `PAID`              VARCHAR(10),
    `PARTICIPANTLIMIT`  INT,
    `PUBLISHEDON`       DATETIME,
    `REQUESTMODERATION` VARCHAR(10),
    `STATE`             VARCHAR(20),
    `CATEGORY_ID`       LONG,
    `INITIATOR_ID`      LONG
);

CREATE TABLE IF NOT EXISTS `COMPILATIONS`
(
    `ID`     LONG PRIMARY KEY AUTO_INCREMENT,
    `TITLE`  VARCHAR(100),
    `PINNED` VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS `REQUESTS`
(
    `ID`           LONG PRIMARY KEY AUTO_INCREMENT,
    `EVENTS_ID`    LONG,
    `REQUESTER_ID` LONG,
    `STATUS`       VARCHAR(20),
    `CREATED`      DATETIME
);

CREATE TABLE `COMPILATIONS_EVENTS`
(
    `EVENTS_ID`      LONG,
    `COMPILATION_ID` LONG,
    PRIMARY KEY (`EVENTS_ID`, `COMPILATION_ID`)
);

ALTER TABLE `EVENTS`
    ADD FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORIES` (`ID`);

ALTER TABLE `EVENTS`
    ADD FOREIGN KEY (`INITIATOR_ID`) REFERENCES `USERS` (`ID`);

ALTER TABLE `REQUESTS`
    ADD FOREIGN KEY (`EVENTS_ID`) REFERENCES `EVENTS` (`ID`);

ALTER TABLE `REQUESTS`
    ADD FOREIGN KEY (`REQUESTER_ID`) REFERENCES `USERS` (`ID`);

ALTER TABLE `COMPILATIONS_EVENTS` ADD FOREIGN KEY (`EVENTS_ID`) REFERENCES `EVENTS` (`ID`);

ALTER TABLE `COMPILATIONS_EVENTS` ADD FOREIGN KEY (`COMPILATION_ID`) REFERENCES `COMPILATIONS` (`ID`);